# set pretrained as a file path or an url
pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth'

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 32

# vit: 'large'
# vit_grad_ckpt: True
# vit_ckpt_layer: 5
# batch_size: 16
# init_lr: 2e-6

image_size: 384

# generation configs
max_length: 143
min_length: 50
num_beams: 3
prompt: 'Findings: '

log_interval: 600
save_interval: 6000
grad_accumulation_steps: 1
max_grad_norm: 1.0

# optimizer
weight_decay: 0.05
init_lr: 1e-5
min_lr: 0

max_epochs: 10
max_steps: 100000
warmup_steps: 3000
