train:
  Resize:
    size: 224
  RandomResizedCrop:
    size: 224
    scale: [0.8, 1.1]
  RandomAffine:
    degrees: 5
    translate: [0.05, 0.05]
    scale: [0.95, 1.05]
valid:
  Resize:
    size: 224
  CenterCrop:
    size: 224
test:
  Resize:
    size: 224
  CenterCrop:
    size: 224
