name: "finetune_classifier"
load_backbone_weights: "./output/cxr_clip_best_loss.pt"
freeze_backbone_weights: true

image_encoder:
  source: "huggingface"
  name: 'microsoft/swin-tiny-patch4-window7-224'
  pretrained: true
  model_type: 'swin'

classifier:
  config:
    name: "mlp" # one of { "linear", "mlp" }
    hidden_dim: 384
    n_class: 14
