image_size: 224
max_length: 128

batch_size: 32
init_lr: 1e-5
min_lr: 1e-6
warmup_lr: 1e-7
weight_decay: 0.05

scheduler_type: cosine_restarts
restarts_t_mult: 1

max_grad_norm: 1
gradient_accumulation_steps: 1

log_interval: 200
save_interval: 10000
warmup_steps: 2000
max_epochs: 30
