image_size: 224
max_length: 256

batch_size: 16
init_lr: 5e-6  # lower learning rate for fine-tuning
min_lr: 1e-6
warmup_lr: 1e-7
weight_decay: 0.02

scheduler_type: cosine
restarts_t_mult: 1

max_grad_norm: 1
gradient_accumulation_steps: 1

log_interval: 10
save_interval: 500
warmup_steps: 500
max_epochs: 20